// <auto-generated />
namespace AbstractTravelAgencyServiceImplementDataBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class infoMesMigr2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(infoMesMigr2));
        
        string IMigrationMetadata.Id
        {
            get { return "201905111051265_infoMesMigr2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
